url:
  sts: https://hom-sts-int.mbi.cloud.ihf/api/oauth/token

aws:
  accessKeyId: ${AWS_ACCESS_KEY}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  region: sa-east-1
  dynamodb:
    endpoint: http://localhost:4566
  sqs:
    endpoint: http://localhost:4566/000000000000/

api:
  client:
    proposta:
      url: https://api-sp.hom.aws.cloud.ihf/hom/servicocontrat-contratacao/v1
      gtw-id: lg7b23ek53
    cliente:
      url: https://servicos-emprestimospessoafisica.svc3.hom.aws.cloud.ihf/clientes/v1/clientes
      gtw-id: 9sh50ut441
    conectorjornadas:
      criar:
        url: https://criar-intencao-v1-conector-jornadas.api-sp.hom.aws.cloud.ihf
      atualizar:
        url: https://atualizar-intencao-v1-conector-jornadas.api-sp.hom.aws.cloud.ihf

sts:
  internal-url: https://hom-sts-int.mbi.cloud.ihf/api/oauth/token
  external-url: https://hom-sts-int.mbi.cloud.ihf/api/oauth/token
  wallet:
    aws:
      secret-manager-arn: ${ARN_SECRET_MANAGERT}

datamesh:
  account-number: 632556220766